### PR TITLE
Support Visual C++ 2015

### PR DESCRIPTION
**Pull request by bgrainger**
* Add `platform.h` with macros to support GCC-specific attributes (and MSVC equivalents where possible)
* Implement `__builtin_clz` etc.
* Add NMAKE makefile
* Add VS2015 solution and projects
* Fix minor source incompatibilities with VC++ 2015

Tested Debug and Release x64 builds on Windows 10 using CL `Version 19.00.23506 for x64`; all tests run by `unit.exe` pass. Also tested with gcc 4.8.4 on Ubuntu 14.04 to ensure no functionality regressions.

### CODE REVIEW

**Comment by lemire** [comment]
Excellent. Give me a few days to review.

**Comment by bgrainger** [comment]
BTW I'm happy to make any modifications you need (to fit with general coding guidelines, improve cross-platform support, etc.); just let me know.

**Comment by lemire** [comment]
Much appreciated. As I wrote, give me a few days to review.

**Comment by lemire** [comment]
I'm not forgetting this...

**Comment by lemire** [comment]
Looks good to me. I am merging. 

I'll add your name to the readme.

**Comment by lemire** [comment]
@bgrainger 

As far as I can tell, your work was flawless.

**Pull request merged**
